### ISSUE TITLE
come up with a name for the app

### ISSUE THREAD

**Issue by EvanHahn** [EvanHahn/EECS-481-chess#1]

**Comment by wvwood** [comment]
Graceful Chess,
Chess with Grace,
Accessible Chess

**Comment by EvanHahn** [comment]
i like Graceful Chess

**Comment by ghost** [comment]
Me too —
Joshua Yu 
joshuasyu@gmail.com

**Comment by korona** [comment]
I'm for Graceful Chess

**Comment by ramstlau** [comment]
That's fine with me also.
